name: deploy-expiration

on:
  push:
    branches:
      - main
    paths:
      - 'expiration/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t rivva/expiration .
      - run: echo "$DOCKER_USER_NAME $DOCKER_PASSWORD" && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push rivva/expiration
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 03d9827e-caf2-4140-a456-6f209f9a8b27
      - run: kubectl rollout restart deployment expiration-depl