name: deploy-paymeclientnts

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && docker build -t rivva/client .
      - run: echo "$DOCKER_USER_NAME $DOCKER_PASSWORD" && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push rivva/client
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save f73215a5-2728-47d8-ae01-9125f48ddf60
      - run: kubectl rollout restart deployment client-depl