name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 9cb33536-60ca-4000-9892-1a9e0b454240
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
