name: deploy-orders

on:
  push:
    branches:
      - main
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t rivva/orders .
      - run: echo "$DOCKER_USER_NAME $DOCKER_PASSWORD" && docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push rivva/orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 9cb33536-60ca-4000-9892-1a9e0b454240
      - run: kubectl rollout restart deployment orders-depl